---
# --------------------------------

- name: "Bootstrap role"
  ansible.builtin.include_role:
    name: ansible-role-distro-{{ ct_distro }}
    apply:
      tags:
      - always
  tags: [ct-osbootstrap]

# --------------------------------
...
